Task/schedule doc
CanalTP/navitia_sdk_docs pull request #9
Opened 2021-04-21 14:44 UTC by MikePetitfils

2021-04-21 14:53 UTC, EvenModiguy requested changes

2021-04-21 14:53 UTC, EvenModiguy commented on schedule/@schedule.md
> +nav_order: 2
use this instead:
```suggestion
nav_order: 5
```

2021-04-21 14:53 UTC, EvenModiguy commented on schedule/ios/1.0.0/communicating_with.md
> +---
Please remove this file if there is no documentation.

2021-04-21 14:53 UTC, EvenModiguy commented on schedule/ios/@ios.md
> +--- -->
Please remove those comments.

2021-04-21 14:53 UTC, EvenModiguy commented on schedule/ios/1.0.0/getting_started.md
> +nav_order: 2
Use this instead.
```suggestion
nav_order: 1
```

2021-04-21 14:53 UTC, EvenModiguy commented on schedule/ios/1.0.0/screens.md
> +nav_order: 3
Use this instead
```suggestion
nav_order: 2
```

2021-09-13 09:00 UTC, RachikAbidi approved these changes

2021-09-13 09:00 UTC, merged